fix: mdstore: fix MetadataStore.dumps(format="md")
MetadataStore.dumps(format="md") was failing with

    TypeError: Object of type dict_items is not JSON serializable

... because self.items() returns dictitems() - while only a dict would be serializable into JSON.

Convert the dictitems back into a dict.